# Generated by Django 5.1 on 2024-10-26 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_initial'),
        ('products', '0007_remove_product_price_remove_product_size_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.sizevariant'),
        ),
    ]
