# Generated by Django 5.1 on 2024-10-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
