version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DEBUG=True

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: resysabu000
      POSTGRES_DB: sweettooth_project
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed_data.sql:/docker-entrypoint-initdb.d/sweettooth.sql
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/ssl/certs/cert.pem
      - ./key.pem:/etc/ssl/private/key.pem
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data: