# Generated by Django 5.1 on 2024-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.CharField(max_length=100),
        ),
    ]
