# Generated by Django 5.1 on 2024-10-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_address_house_no_alter_address_pin_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
