# Generated by Django 5.1 on 2024-10-16 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_size_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='products.product'),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='stock',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='price',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='sizevariant',
            unique_together={('product', 'size_name')},
        ),
    ]
